#ifndef SPI_CONFIG_H
#define SPI_CONFIG_H

#include "GPIO_interface.h"

#define MSPI1_MOSI_PORTPIN		GPIOA_PORT,PIN_7
#define MSPI1_MISO_PORTPIN		GPIOA_PORT,PIN_6
#define MSPI1_SCK_PORTPIN		GPIOA_PORT,PIN_5
#define MSPI1_NSS_PORTPIN		GPIOA_PORT,PIN_4

#endif
